name: MCMMOCredits
version: '0.3.4-SNAPSHOT'
main: games.cultivate.mcmmocredits.MCMMOCredits
api-version: 1.19
description: The essential MCMMO Credits plugin.
author: CultivateGames
website: https://cultivate.games/
softdepend: [mcMMO, PlaceholderAPI]
