name: MCMMOCredits
version: '0.0.2-SNAPSHOT'
main: games.cultivate.mcmmocredits.MCMMOCredits
api-version: 1.18
description: The essential MCMMO Credits plugin.
author: CultivateGames
website: https://cultivate.games/
softdepend: [mcMMO, PlaceholderAPI]
