name: MCMMOCredits
version: '${project.version}'
main: games.cultivate.mcmmocredits.MCMMOCredits
api-version: 1.17
description: The essential MCMMO Credits plugin.
author: CultivateGames
website: https://cultivate.games/
softdepend: [mcMMO, PlaceholderAPI]