name: "Full Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    name: "Full Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Project
        run: ./gradlew build

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "MCMMO Credits Release"
          files: |
                        build/libs/*.jar
