name: "MCMMO Credits Build Process"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    name: "MCMMO Credits Build Process"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build Project
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace

      - name: Publish
        if: ${{ runner.os == 'Linux' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: "./gradlew publish"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "MCMMO Credits Release"
          files: |
                        build/libs/*.jar
